{"uuid": "bcada259-27f9-4ede-9278-fb16f059ec30", "children": ["849d5510-df42-4557-b5e3-ea0f47586893"], "befores": [{"name": "xunit_setup_class_fixture_TestUserAdd", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 94\nCurrent browser version is 96.0.4664.110 with binary path C:\\Users\\13641\\AppData\\Local\\Google\\Chrome\\Application\\chrome.exe\n\n", "trace": "  File \"c:\\program files\\python\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"c:\\program files\\python\\lib\\site-packages\\_pytest\\fixtures.py\", line 1126, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"c:\\program files\\python\\lib\\site-packages\\_pytest\\fixtures.py\", line 925, in call_fixture_func\n    fixture_result = next(generator)\n  File \"c:\\program files\\python\\lib\\site-packages\\_pytest\\python.py\", line 811, in xunit_setup_class_fixture\n    _call_with_optional_argument(func, self.obj)\n  File \"c:\\program files\\python\\lib\\site-packages\\_pytest\\python.py\", line 739, in _call_with_optional_argument\n    func(arg)\n  File \"F:\\python\\社区版\\work\\hm-webUI01\\testpage\\test_add_user.py\", line 17, in setup_class\n    self.login = Hzb_Login()\n  File \"F:\\python\\社区版\\work\\hm-webUI01\\page\\hzb_login.py\", line 60, in __init__\n    self.login_handle = LoginHandle()\n  File \"F:\\python\\社区版\\work\\hm-webUI01\\page\\hzb_login.py\", line 39, in __init__\n    self.login_page = LoginPage()\n  File \"F:\\python\\社区版\\work\\hm-webUI01\\page\\hzb_login.py\", line 14, in __init__\n    super().__init__()\n  File \"F:\\python\\社区版\\work\\hm-webUI01\\base\\base.py\", line 8, in __init__\n    self.driver = UtilWebdriver.houtai_driver()\n  File \"F:\\python\\社区版\\work\\hm-webUI01\\common\\web_util.py\", line 15, in houtai_driver\n    self.qd = webdriver.Chrome()\n  File \"c:\\program files\\python\\lib\\site-packages\\selenium\\webdriver\\chrome\\webdriver.py\", line 81, in __init__\n    desired_capabilities=desired_capabilities)\n  File \"c:\\program files\\python\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 157, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"c:\\program files\\python\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 252, in start_session\n    response = self.execute(Command.NEW_SESSION, parameters)\n  File \"c:\\program files\\python\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"c:\\program files\\python\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1650029727008, "stop": 1650029730958}], "start": 1650029727008, "stop": 1650029731068}